feat: add release creation and Kafka distribution retrieval steps to workflow

diff --git a/.github/workflows/build-patched-kafka.yaml b/.github/workflows/build-patched-kafka.yaml
--- a/.github/workflows/build-patched-kafka.yaml
+++ b/.github/workflows/build-patched-kafka.yaml
@@ -114,9 +114,37 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Create release
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ inputs.tag }}
+          draft: false
+          prerelease: false
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Upload failed test report
         if: failure() # Выполнится только если шаг выше завершился ошибкой
         uses: actions/upload-artifact@v4
         with:
           name: core-test-report
           path: core/build/reports/tests/test/
+
+      - name: Get kafka distribution artifact
+        run: |
+          KAFKA_DISTRO=$(find core/build/distributions/ -name "kafka_[0-9.-]*.tgz" | head -n 1 | xargs -I {} basename {})
+          if [ -f "$KAFKA_DISTRO" ]; then
+            echo "Found Kafka distribution: $KAFKA_DISTRO"
+            echo "KAFKA_DISTRO=$KAFKA_DISTRO" >> $GITHUB_ENV
+          else
+            echo "Kafka distribution not found!"
+            exit 1
+          fi
+      - name: Trigger Qubership Kafka Docker Build
+        uses: netcracker/qubership-workflow-hub/actions/custom-event@v1.0.7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          owner: ${{ github.repository_owner }}
+          repo: qubership-kafka
+          event-type: kafka-patched-build
+          client-payload: '{"kafkaVersion": "${{ inputs.kafka-tag }}", "scalaVersion": "${{ inputs.scalaVersion }}", "javaVersion": "${{ inputs.javaVersion }}", "tag": "${{ inputs.tag }}", "kafka-distro-url": "https://github.com/${{ github.repository_owner }}/kafka-patches/releases/download/${{ inputs.tag }}/${{ env.KAFKA_DISTRO }}"}'
